steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    dir: pkg/adminserver/web
    args:
      - --destination=gcr.io/$PROJECT_ID/tuber-frontend:$BRANCH_NAME
      - --destination=gcr.io/$PROJECT_ID/tuber-frontend:$COMMIT_SHA
      - --cache=true
