steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/tuber:$BRANCH_NAME
      - --destination=gcr.io/$PROJECT_ID/tuber:$COMMIT_SHA
      - --cache=true