steps:
  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args:
      - --destination=gcr.io/$PROJECT_ID/tuber:$BRANCH_NAME
      - --destination=gcr.io/$PROJECT_ID/tuber:$COMMIT_SHA
      - --cache=true
