apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuber-frontend
  namespace: tuber-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuber-frontend
  template:
    metadata:
      labels:
        app: tuber-frontend
    spec:
      containers:
        - image: "{{ .tuberImage }}"
          name: tuber-frontend
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
