apiVersion: apps/v1
kind: Pod
metadata:
  name: tuber-bolter
  namespace: tuber
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: "default-pool"
  serviceAccountName: tuber
  terminationGracePeriodSeconds: 1200
  containers:
    - image: "gcr.io/freshly-docker/tuber:main"
      name: tuber
      command:
        - "/app/tuber"
        - "bolter"
      resources:
        requests:
          memory: "128Mi"
          cpu: "1"
        limits:
          memory: "256Mi"
          cpu: "1"
      volumeMounts:
        - name: tuber-credentials
          readOnly: true
          mountPath: "/etc/tuber-credentials"
        - name: tuber-bolt
          mountPath: "/etc/tuber-bolt"
      envFrom:
        - secretRef:
            name: tuber-env
      ports:
        - containerPort: 3000
  volumes:
    - name: tuber-credentials
      secret:
        secretName: tuber-credentials.json
    - name: tuber-bolt
      persistentVolumeClaim:
        claimName: tuber
