apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuber
  name: tuber
  namespace: tuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuber
  template:
    metadata:
      labels:
        app: tuber
    spec:
      containers:
      - image: gcr.io/freshly-docker/tuber:30f9efab987c7df585f8526d2c2fd015cf06cf48
        name: tuber
      volumes:
        - name: tuber-credentials
          secret:
            secretName: tuber-credentials.json
