apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuber
  name: tuber
  namespace: tuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuber
  template:
    metadata:
      labels:
        app: tuber
    spec:
      containers:
      - image: gcr.io/freshly-docker/tuber@master
        name: tuber
        volumeMounts:
          - name: tuber-credentials
            readOnly: true
            mountPath: "/etc/tuber-credentials"
      volumes:
        - name: tuber-credentials
          secret:
            secretName: tuber-credentials.json
