apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tuber
  name: tuber
  namespace: tuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuber
  template:
    metadata:
      labels:
        app: tuber
    spec:
      containers:
      - image: {{ .tuberImage }}
        name: tuber
        volumeMounts:
          - name: tuber-credentials
            readOnly: true
            mountPath: "/etc/tuber-credentials"
        envFrom:
          - configMapRef:
              name: tuber-config
      volumes:
        - name: tuber-credentials
          secret:
            secretName: tuber-credentials.json
