apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuber
  namespace: tuber
  annotations:
    "tuber/rolloutTimeout": 30m
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuber
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: tuber
    spec:
      serviceAccountName: tuber
      containers:
      - image: "{{ .tuberImage }}"
        name: tuber
        volumeMounts:
          - name: tuber-credentials
            readOnly: true
            mountPath: "/etc/tuber-credentials"
        envFrom:
          - secretRef:
              name: tuber-env
      volumes:
        - name: tuber-credentials
          secret:
            secretName: tuber-credentials.json
