apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tuber
  namespace: tuber
spec:
  hosts:
    - production.admin.freshlyservices.net
  gateways:
    - istio-system/iap-gateway
  http:
    - route:
        - destination:
            host: tuber
            port:
              number: 3000
      match:
        - uri:
            prefix: /tuber/graphql
    - route:
        - destination:
            host: tuber-frontend.tuber-frontend.svc.cluster.local
            port:
              number: 3000
      match:
        - uri:
            prefix: /tuber
