apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tuber
spec:
  hosts:
  - "tuber.{{.clusterDefaultHost}}"
  gateways:
  - "{{.clusterDefaultGateway}}"
  http:
  - route:
    - destination:
        host: tuber
