apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tuber
spec:
  hosts:
    - "{{.clusterAdminHost}}"
  gateways:
    - "{{.clusterAdminGateway}}"
  http:
    - route:
        - destination:
            host: tuber
            port:
              number: 3000
      match:
        - uri:
            prefix: /tuber/graphql
    - route:
        - destination:
            host: tuber-frontend.tuber-frontend
            port:
              number: 3000
      match:
        - uri:
            prefix: /tuber
