// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/tuber_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReviewAppRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	Branch               string   `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewAppRequest) Reset()         { *m = CreateReviewAppRequest{} }
func (m *CreateReviewAppRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReviewAppRequest) ProtoMessage()    {}
func (*CreateReviewAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb9660b46a6499f, []int{0}
}

func (m *CreateReviewAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewAppRequest.Unmarshal(m, b)
}
func (m *CreateReviewAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewAppRequest.Marshal(b, m, deterministic)
}
func (m *CreateReviewAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewAppRequest.Merge(m, src)
}
func (m *CreateReviewAppRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReviewAppRequest.Size(m)
}
func (m *CreateReviewAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewAppRequest proto.InternalMessageInfo

func (m *CreateReviewAppRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateReviewAppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *CreateReviewAppRequest) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

type CreateReviewAppResponse struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReviewAppResponse) Reset()         { *m = CreateReviewAppResponse{} }
func (m *CreateReviewAppResponse) String() string { return proto.CompactTextString(m) }
func (*CreateReviewAppResponse) ProtoMessage()    {}
func (*CreateReviewAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb9660b46a6499f, []int{1}
}

func (m *CreateReviewAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReviewAppResponse.Unmarshal(m, b)
}
func (m *CreateReviewAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReviewAppResponse.Marshal(b, m, deterministic)
}
func (m *CreateReviewAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReviewAppResponse.Merge(m, src)
}
func (m *CreateReviewAppResponse) XXX_Size() int {
	return xxx_messageInfo_CreateReviewAppResponse.Size(m)
}
func (m *CreateReviewAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReviewAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReviewAppResponse proto.InternalMessageInfo

func (m *CreateReviewAppResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *CreateReviewAppResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteReviewAppRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AppName              string   `protobuf:"bytes,2,opt,name=appName,proto3" json:"appName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReviewAppRequest) Reset()         { *m = DeleteReviewAppRequest{} }
func (m *DeleteReviewAppRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewAppRequest) ProtoMessage()    {}
func (*DeleteReviewAppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb9660b46a6499f, []int{2}
}

func (m *DeleteReviewAppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewAppRequest.Unmarshal(m, b)
}
func (m *DeleteReviewAppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewAppRequest.Marshal(b, m, deterministic)
}
func (m *DeleteReviewAppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewAppRequest.Merge(m, src)
}
func (m *DeleteReviewAppRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewAppRequest.Size(m)
}
func (m *DeleteReviewAppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewAppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewAppRequest proto.InternalMessageInfo

func (m *DeleteReviewAppRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteReviewAppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type DeleteReviewAppResponse struct {
	AppName              string   `protobuf:"bytes,1,opt,name=appName,proto3" json:"appName,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReviewAppResponse) Reset()         { *m = DeleteReviewAppResponse{} }
func (m *DeleteReviewAppResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReviewAppResponse) ProtoMessage()    {}
func (*DeleteReviewAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb9660b46a6499f, []int{3}
}

func (m *DeleteReviewAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReviewAppResponse.Unmarshal(m, b)
}
func (m *DeleteReviewAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReviewAppResponse.Marshal(b, m, deterministic)
}
func (m *DeleteReviewAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReviewAppResponse.Merge(m, src)
}
func (m *DeleteReviewAppResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReviewAppResponse.Size(m)
}
func (m *DeleteReviewAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReviewAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReviewAppResponse proto.InternalMessageInfo

func (m *DeleteReviewAppResponse) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *DeleteReviewAppResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateReviewAppRequest)(nil), "proto.CreateReviewAppRequest")
	proto.RegisterType((*CreateReviewAppResponse)(nil), "proto.CreateReviewAppResponse")
	proto.RegisterType((*DeleteReviewAppRequest)(nil), "proto.DeleteReviewAppRequest")
	proto.RegisterType((*DeleteReviewAppResponse)(nil), "proto.DeleteReviewAppResponse")
}

func init() {
	proto.RegisterFile("pkg/proto/tuber_service.proto", fileDescriptor_deb9660b46a6499f)
}

var fileDescriptor_deb9660b46a6499f = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x50, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0x6e, 0x94, 0xad, 0x3a, 0x17, 0x21, 0xc8, 0x36, 0x14, 0x2a, 0x92, 0x93, 0xa7, 0x16, 0xf4,
	0x09, 0x44, 0x0f, 0x8a, 0xe0, 0x21, 0x78, 0xd7, 0x6c, 0x19, 0x6c, 0xa9, 0x26, 0x71, 0x92, 0xd6,
	0xc7, 0xf2, 0x15, 0x25, 0xc9, 0xba, 0xe8, 0xfe, 0x9c, 0x7a, 0x0a, 0xdf, 0x4c, 0xe6, 0xfb, 0x83,
	0x99, 0xdb, 0xbc, 0x2d, 0x1c, 0xd9, 0x60, 0x17, 0x61, 0x5b, 0x21, 0xbd, 0x78, 0xa4, 0xdd, 0x7a,
	0x89, 0xf3, 0x34, 0xe3, 0x45, 0x7a, 0xe4, 0x2b, 0x94, 0xb7, 0x84, 0x3a, 0xa0, 0xc2, 0xdd, 0x1a,
	0xbf, 0x6e, 0x9c, 0x53, 0xf8, 0xb9, 0x45, 0x1f, 0xf8, 0x19, 0x14, 0xc1, 0x6e, 0xd0, 0x08, 0x76,
	0xc1, 0x2e, 0x4f, 0x54, 0x06, 0x5c, 0xc0, 0x91, 0x76, 0xee, 0x49, 0x7f, 0xa0, 0x38, 0x48, 0xf3,
	0x5f, 0xc8, 0x4b, 0x18, 0x57, 0xa4, 0xcd, 0x72, 0x25, 0x0e, 0xd3, 0xa2, 0x46, 0xf2, 0x11, 0x26,
	0x1d, 0x05, 0xef, 0xac, 0xf1, 0xc8, 0xa7, 0x70, 0xbc, 0xb2, 0x3e, 0x98, 0xc8, 0x96, 0x55, 0x1a,
	0x1c, 0xe5, 0x91, 0xc8, 0x52, 0x2d, 0x93, 0x81, 0xbc, 0x87, 0xf2, 0x0e, 0xdf, 0x71, 0x7f, 0xbb,
	0xf2, 0x01, 0x26, 0x1d, 0xa6, 0xda, 0xd6, 0x9f, 0x23, 0xf6, 0x3f, 0x63, 0xaf, 0xa9, 0xab, 0x6f,
	0x06, 0xc5, 0x73, 0xac, 0x98, 0x2b, 0x38, 0x6d, 0x65, 0xe5, 0xb3, 0xdc, 0xf7, 0xbc, 0xbf, 0xe5,
	0xe9, 0xf9, 0xd0, 0x3a, 0x7b, 0x91, 0xa3, 0xc8, 0xd9, 0x32, 0xda, 0x70, 0xf6, 0x57, 0xd1, 0x70,
	0x0e, 0xe4, 0x93, 0xa3, 0x6a, 0x9c, 0x3e, 0x5c, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x08, 0x0f,
	0x6d, 0x31, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TuberClient is the client API for Tuber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TuberClient interface {
	CreateReviewApp(ctx context.Context, in *CreateReviewAppRequest, opts ...grpc.CallOption) (*CreateReviewAppResponse, error)
	DeleteReviewApp(ctx context.Context, in *DeleteReviewAppRequest, opts ...grpc.CallOption) (*DeleteReviewAppResponse, error)
}

type tuberClient struct {
	cc grpc.ClientConnInterface
}

func NewTuberClient(cc grpc.ClientConnInterface) TuberClient {
	return &tuberClient{cc}
}

func (c *tuberClient) CreateReviewApp(ctx context.Context, in *CreateReviewAppRequest, opts ...grpc.CallOption) (*CreateReviewAppResponse, error) {
	out := new(CreateReviewAppResponse)
	err := c.cc.Invoke(ctx, "/proto.Tuber/CreateReviewApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tuberClient) DeleteReviewApp(ctx context.Context, in *DeleteReviewAppRequest, opts ...grpc.CallOption) (*DeleteReviewAppResponse, error) {
	out := new(DeleteReviewAppResponse)
	err := c.cc.Invoke(ctx, "/proto.Tuber/DeleteReviewApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TuberServer is the server API for Tuber service.
type TuberServer interface {
	CreateReviewApp(context.Context, *CreateReviewAppRequest) (*CreateReviewAppResponse, error)
	DeleteReviewApp(context.Context, *DeleteReviewAppRequest) (*DeleteReviewAppResponse, error)
}

// UnimplementedTuberServer can be embedded to have forward compatible implementations.
type UnimplementedTuberServer struct {
}

func (*UnimplementedTuberServer) CreateReviewApp(ctx context.Context, req *CreateReviewAppRequest) (*CreateReviewAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReviewApp not implemented")
}
func (*UnimplementedTuberServer) DeleteReviewApp(ctx context.Context, req *DeleteReviewAppRequest) (*DeleteReviewAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReviewApp not implemented")
}

func RegisterTuberServer(s *grpc.Server, srv TuberServer) {
	s.RegisterService(&_Tuber_serviceDesc, srv)
}

func _Tuber_CreateReviewApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReviewAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuberServer).CreateReviewApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tuber/CreateReviewApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuberServer).CreateReviewApp(ctx, req.(*CreateReviewAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tuber_DeleteReviewApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReviewAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TuberServer).DeleteReviewApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tuber/DeleteReviewApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TuberServer).DeleteReviewApp(ctx, req.(*DeleteReviewAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tuber_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tuber",
	HandlerType: (*TuberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReviewApp",
			Handler:    _Tuber_CreateReviewApp_Handler,
		},
		{
			MethodName: "DeleteReviewApp",
			Handler:    _Tuber_DeleteReviewApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/tuber_service.proto",
}
